pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'limantha091/devopsapp:latest'
        DOCKER_HUB_CREDENTIALS_ID = 'dockerhub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/LingarajMantha/DevopsProject33_limantha.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('DevOps-Project-33/DevSecOps-CI-CD-Pipeline') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('DevOps-Project-33/DevSecOps-CI-CD-Pipeline') {
                    sh 'docker build -t limantha091/devopsapp:latest .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    dir('DevOps-Project-33/DevSecOps-CI-CD-Pipeline') {
                        sh '''
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker push limantha091/devopsapp:latest
                        '''
                    }
                }
            }
        }
    }
}

